apiVersion: v1
appVersion: "1.0.0"
description: "Universal Worker Service API Server"
name: uws-api-server
version: "1.3.1"
home: https://github.com/lsst-dm/uws-api-server
maintainers:
  - name: Timothy Andrew Manning
    email: manninga@illinois.edu
