# Default values for uws-api-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: lsstdm/uws-api-server
  tag: dev

# Target Kubernetes cluster. Supported values are NCSA Test Stand ("nts") and NCSA Integration ("int")
targetCluster: ""

# The subpath under /project to mount in the job containers
projectSubpath: ""
