# Default values for uws-api-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: lsstdm/uws-api-server
  tag: latest

# Target Kubernetes cluster. Supported values are NCSA Test Stand ("nts") and NCSA Integration ("int")
targetCluster: ""
