# Default values for uws-api-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: lsstdm/uws-api-server
  tag: latest

# Target Kubernetes cluster
targetCluster: ""
hostname: ""
basePath: "uws-server"

# Log level of server. Set to "DEBUG" for highest verbosity.
logLevel: "WARNING"

server:
  securityContext:
    runAsUser: 1000
    runAsGroup: 202
    fsGroup: 202

job:
  image:
    repository: "lsstsqre/centos"
    tag: "d_latest"
  securityContext:
    runAsUser: 1000
    runAsGroup: 202
    fsGroup: 202

# Central data volumes to be mounted in job containers
volumes: []
# - name: repo
#   claimName: repo-pvc
#   mountPath: "/repo"
#   subPath: ""
#   readOnly: false

# Server working directory to store generated job data
workingVolume:
  name: job-files
  claimName: ""
  mountPath: "/uws"
  subPath: ""
