---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-job-scripts
  labels:
    app: {{ template "uws-api-server.fullname" . }}
    chart: {{ template "uws-api-server.chart" . }}
data:
  init.sh: |-
    #!/bin/bash -e

    source /opt/lsst/software/stack/loadLSST.bash
    setup lsst_distrib
    
    # Reference: https://pipelines.lsst.io/install/demo.html
    cd "${UWS_TEST_DIR}"
    setup -r .
    ./bin/run_demo.sh