apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "uws-api-server.fullname" . }}
  labels:
    app: {{ template "uws-api-server.fullname" . }}
    chart: {{ template "uws-api-server.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "uws-api-server.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "uws-api-server.fullname" . }}
    spec:
      serviceAccountName: job-manager
      volumes:
      - name: job-files
        persistentVolumeClaim:
          claimName: nfs-scratch-pvc
      containers:
      - name: uws-api-server
        # securityContext:
        #   runAsUser: 1001
        #   runAsGroup: 1001
          # fsGroup: 73006
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        command: ["/bin/bash", "-c", "cd server && python3 server.py"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: job-files
          mountPath: /uws
        env:
          - name: "UWS_ROOT_DIR"
            value: "/uws"
          - name: API_DOMAIN
            value: {{ template "uws-api-server.fullname" . }}
          - name: API_PORT
            value: "8080"
          - name: LOG_LEVEL
            value: "DEBUG"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uws-api-client
  labels:
    app: uws-api-client
    chart: {{ template "uws-api-server.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: uws-api-client
  template:
    metadata:
      labels:
        app: uws-api-client
    spec:
      containers:
      - name: uws-api-client
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        command: ["/bin/bash", "-c", "sleep 1000d"]
        env:
          - name: API_DOMAIN
            value: {{ template "uws-api-server.fullname" . }}
          - name: API_PORT
            value: "80"
