{{- if .Values.targetCluster }}
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: uws-server
  namespace: uws
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: uws-server-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
spec:
  rules:
    - host: lsst-nts-k8s.ncsa.illinois.edu
      http:
        paths:
          - path: /uws-server(/|$)(.*)
            pathType: Prefix
            backend:
              serviceName: uws-server
              servicePort: 80
{{- end }}
