---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "uws-api-server.fullname" $ }}-uws-server
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: uws-server-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
spec:
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /{{ .Values.basePath }}(/|$)(.*)
            backend:
              serviceName: {{ .Release.Name }}-server
              servicePort: 80
