apiVersion: batch/v1
kind: Job
metadata:
  name: uws-api-client
  labels:
    app: uws-api-client
    chart: {{ template "uws-api-server.chart" . }}
spec:
  selector:
    matchLabels:
      app: uws-api-client
  template:
    metadata:
      labels:
        app: uws-api-client
    spec:
      restartPolicy: Never
      containers:
      - name: uws-api-client
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        command: ["/bin/bash", "-c", "cd client && python3 client.py"]
        env:
          - name: API_DOMAIN
            value: {{ template "uws-api-server.fullname" . }}
          - name: API_PORT
            value: "8080"
        