---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-manager

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: job-manager-role
rules:
  - apiGroups: ["batch"]
    resources: ["jobs", "jobs/status", "configmaps"]
    verbs: ["get", "list", "watch", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: job-manager-rolebinding
roleRef:
  kind: Role
  name: job-manager-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: job-manager