{{ if eq .Values.targetCluster "nts" }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "uws-api-server.fullname" . }}-nfs-data-pv
  labels:
    app: {{ template "uws-api-server.fullname" . }}
    chart: {{ template "uws-api-server.chart" . }}
    name: {{ template "uws-api-server.chart" . }}-nfs-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: lsst-nfs.ncsa.illinois.edu
    path: /offline/teststand
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "uws-api-server.fullname" . }}-nfs-data-pvc
  labels:
    app: {{ template "uws-api-server.fullname" . }}
    chart: {{ template "uws-api-server.chart" . }}
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadOnlyMany
  storageClassName: ""
  selector:
    matchLabels:
      name: {{ template "uws-api-server.chart" . }}-nfs-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "uws-api-server.fullname" . }}-nfs-scratch-pv
  labels:
    app: {{ template "uws-api-server.fullname" . }}
    chart: {{ template "uws-api-server.chart" . }}
    name: {{ template "uws-api-server.chart" . }}-nfs-scratch
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: lsst-l1-cl-arctl.ncsa.illinois.edu
    path: /scratch/uws
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "uws-api-server.fullname" . }}-nfs-scratch-pvc
  labels:
    app: {{ template "uws-api-server.fullname" . }}
    chart: {{ template "uws-api-server.chart" . }}
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  selector:
    matchLabels:
      name: {{ template "uws-api-server.chart" . }}-nfs-scratch
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "uws-api-server.fullname" . }}-nfs-oods-comcam-pv
  labels:
    app: {{ template "uws-api-server.fullname" . }}
    chart: {{ template "uws-api-server.chart" . }}
    name: {{ template "uws-api-server.chart" . }}-nfs-oods-comcam
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: lsst-l1-cl-arctl.ncsa.illinois.edu
    path: /data/lsstdata/NTS/comcam/oods/gen3butler/repo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "uws-api-server.fullname" . }}-nfs-oods-comcam-pvc
  labels:
    app: {{ template "uws-api-server.fullname" . }}
    chart: {{ template "uws-api-server.chart" . }}
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  selector:
    matchLabels:
      name: {{ template "uws-api-server.chart" . }}-nfs-oods-comcam
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "uws-api-server.fullname" . }}-nfs-oods-auxtel-pv
  labels:
    app: {{ template "uws-api-server.fullname" . }}
    chart: {{ template "uws-api-server.chart" . }}
    name: {{ template "uws-api-server.chart" . }}-nfs-oods-auxtel
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: lsst-l1-cl-arctl.ncsa.illinois.edu
    path: /data/lsstdata/NTS/auxTel/oods/gen3butler/repo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "uws-api-server.fullname" . }}-nfs-oods-auxtel-pvc
  labels:
    app: {{ template "uws-api-server.fullname" . }}
    chart: {{ template "uws-api-server.chart" . }}
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  selector:
    matchLabels:
      name: {{ template "uws-api-server.chart" . }}-nfs-oods-auxtel
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "uws-api-server.fullname" . }}-repo-pv
  labels:
    app: {{ template "uws-api-server.fullname" . }}
    chart: {{ template "uws-api-server.chart" . }}
    name: {{ template "uws-api-server.chart" . }}-repo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: lsst-nfs.ncsa.illinois.edu
    path: /user/repo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "uws-api-server.fullname" . }}-repo-pvc
  labels:
    app: {{ template "uws-api-server.fullname" . }}
    chart: {{ template "uws-api-server.chart" . }}
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  selector:
    matchLabels:
      name: {{ template "uws-api-server.chart" . }}-repo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "uws-api-server.fullname" . }}-project-pv
  labels:
    app: {{ template "uws-api-server.fullname" . }}
    chart: {{ template "uws-api-server.chart" . }}
    name: {{ template "uws-api-server.chart" . }}-project
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: lsst-nfs.ncsa.illinois.edu
    path: /user/staff/project
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "uws-api-server.fullname" . }}-project-pvc
  labels:
    app: {{ template "uws-api-server.fullname" . }}
    chart: {{ template "uws-api-server.chart" . }}
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  selector:
    matchLabels:
      name: {{ template "uws-api-server.chart" . }}-project

{{ end }}
